version: '2'
services:
    micoserviceapplication-app:
        image: micoserviceapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://micoserviceapplication-mysql:3306/micoserviceapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    micoserviceapplication-mysql:
        extends:
            file: mysql.yml
            service: micoserviceapplication-mysql
